server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para o Backend (Opcional se o Nginx principal já faz isso, mas ajuda no isolamento)
    # location /api {
    #     proxy_pass http://backend-melvin:8080;
    # }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
